package com.an.jetpackcomposesample

object Constants {
    const val NAV_ROUTE_HOME = "home"
    const val NAV_ROUTE_UPDATES = "updates"
    const val NAV_ROUTE_CALLS = "calls"
    const val NAV_ROUTE_CHATS = "chats"
    const val NAV_ROUTE_SETTINGS = "settings"
    const val NAV_ROUTE_NOTIFICATION = "notifications"

    const val NAV_ROUTE_MAIN = "main"
    const val NAV_ROUTE_INTRO = "Intro"
    const val NAV_ROUTE_ROW = "Row"
    const val NAV_ROUTE_COLUMN = "Column"
    const val NAV_ROUTE_TEXT = "Text"
    const val NAV_ROUTE_BUTTON = "Button"
    const val NAV_ROUTE_IMAGE = "Image"
    const val NAV_ROUTE_TEXTFIELD = "TextField"
    const val NAV_ROUTE_GRID = "Grid"
    const val NAV_ROUTE_LIST = "List"
    const val NAV_ROUTE_SCAFFOLD = "Scaffold"
    const val NAV_ROUTE_CARD = "Card"
    const val NAV_ROUTE_PROGRESS = "Progress"
    const val NAV_ROUTE_DIALOG = "Dialog"
    const val NAV_ROUTE_RADIO = "Radio"
    const val NAV_ROUTE_CHECKBOX = "Checkbox"
    const val NAV_ROUTE_OTHERS = "Others"
    const val NAV_ROUTE_TAB = "Tab"
    const val NAV_ROUTE_BOTTOM_BAR = "BottomBar"
    const val NAV_ROUTE_THEMES = "Themes"
}